version: "3.3"

services:

  demo-app-backend:
    image: onurkenis/backend-challange:local
    command: yarn prepare-and-start
    env_file: docker-compose.env
    depends_on:
      - mysql
      - ipfs
    ports:
      - "3000:3000"
    networks:
      - internal

  ipfs:
    image: ipfs/go-ipfs:release
    ports:
      - "4001:4001" # Swarm
      - "5001:5001" # Api
      - "8080:8080" # Gateway
    volumes:
      - ./.ipfs/ipfs0:/data/ipfs
      - ./.ipfs/export:/export
      - ./scripts/start_ipfs:/start_ipfs
    entrypoint: ["/sbin/tini", "--", "/start_ipfs"]
    command: ["daemon", "--migrate=true", "--agent-version-suffix=docker"]
    env_file: docker-compose.env
    networks:
      - internal      

  mysql:
    image: mysql:latest
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app

    ports:
      - 3306:3306
    networks:
      - internal

networks:
  internal:


volumes:
  data:
