version: "3.3"

services:

  demo-app-backend:
    image: onurkenis/backend-challange:local
    command: yarn prepare-and-start
    env_file: docker-compose.env
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - internal

  mysql:
    image: mysql:latest
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app

    ports:
      - 3306:3306
    networks:
      - internal

networks:
  internal:


volumes:
  data:
