version: "3.3"

services:
  mysql:
    image: mysql:latest
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app

    ports:
      - 3306:3306
    networks:
      - internal
      

networks:
  internal:

volumes:
  data:
